export const FETCH_RECIPIES = 'FETCH_RECIPIES';
export const FETCH_RECIPE = 'FETCH_RECIPE';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SAVE_RECIPE = 'SAVE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';